import React from "react";
import Head from "next/head";
import Nav from "../components/Nav";
import Body from "../components/Body";
import Footer from "../components/Footer";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <>
      <Head>
        <title>Weiss Demo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="true"/>
        <link href="https://fonts.googleapis.com/css2?family=Chivo:wght@600&family=League+Spartan:wght@600;700&family=Montserrat&display=swap" rel="stylesheet"/>
      </Head>
      <main className={styles.main}>
        <Nav />
        <Body />
      </main>
      <Footer />
    </>
  );
}
